.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svg:Launcher-github| image:: https://img.shields.io/badge/pyEDAA-Launcher-ffca28.svg?longCache=true&style=flat-square&logo=GitHub&labelColor=ff8f00
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Launcher
.. |SHIELD:png:Launcher-github| image:: https://raster.shields.io/badge/pyEDAA-Launcher-ffca28.svg?longCache=true&style=flat-square&logo=GitHub&labelColor=ff8f00
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Launcher

.. # Sourcecode license
.. |SHIELD:svg:Launcher-src-license| image:: https://img.shields.io/pypi/l/pyEDAA.Launcher?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: License.html
.. |SHIELD:png:Launcher-src-license| image:: https://img.shields.io/pypi/l/pyEDAA.Launcher?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Launcher/blob/main/LICENSE.md

.. # GitHub tag
.. |SHIELD:svg:Launcher-tag| image:: https://img.shields.io/github/v/tag/edaa-org/pyEDAA.Launcher?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Launcher/tags
.. |SHIELD:png:Launcher-tag| image:: https://raster.shields.io/github/v/tag/edaa-org/pyEDAA.Launcher?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Launcher/tags

.. # GitHub release
.. |SHIELD:svg:Launcher-release| image:: https://img.shields.io/github/v/release/edaa-org/pyEDAA.Launcher?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Launcher/releases/latest
.. |SHIELD:png:Launcher-release| image:: https://raster.shields.io/github/v/release/edaa-org/pyEDAA.Launcher?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Launcher/releases/latest

.. # GitHub release date
.. |SHIELD:svg:Launcher-date| image:: https://img.shields.io/github/release-date/edaa-org/pyEDAA.Launcher?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Launcher/releases
.. |SHIELD:png:Launcher-date| image:: https://raster.shields.io/github/release-date/edaa-org/pyEDAA.Launcher?logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Launcher/releases

.. # GitHub/Libraries dependent projects
.. |SHIELD:svg:Launcher-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/pyEDAA.Launcher?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Launcher/network/dependents
.. |SHIELD:png:Launcher-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/pyEDAA.Launcher?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Launcher/network/dependents

.. # GHA test and coverage
.. |SHIELD:svg:Launcher-gha-test| image:: https://img.shields.io/github/actions/workflow/status/edaa-org/pyEDAA.Launcher/Pipeline.yml?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Launcher/actions/workflows/Pipeline.yml
.. |SHIELD:png:Launcher-gha-test| image:: https://raster.shields.io/github/actions/workflow/status/edaa-org/pyEDAA.Launcher/Pipeline.yml?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Launcher/actions/workflows/Pipeline.yml

.. # Codacy - quality
.. |SHIELD:svg:Launcher-codacy-quality| image:: https://img.shields.io/codacy/grade/83936550d5094383bb89bb117c0abbfe?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pyEDAA.Launcher
.. |SHIELD:png:Launcher-codacy-quality| image:: https://raster.shields.io/codacy/grade/83936550d5094383bb89bb117c0abbfe?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pyEDAA.Launcher

.. # Codacy - coverage
.. |SHIELD:svg:Launcher-codacy-coverage| image:: https://img.shields.io/codacy/coverage/83936550d5094383bb89bb117c0abbfe?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pyEDAA.Launcher
.. |SHIELD:png:Launcher-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/83936550d5094383bb89bb117c0abbfe?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pyEDAA.Launcher

.. # Codecov - coverage
.. |SHIELD:svg:Launcher-codecov-coverage| image:: https://img.shields.io/codecov/c/github/edaa-org/pyEDAA.Launcher?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/edaa-org/pyEDAA.Launcher
.. |SHIELD:png:Launcher-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/edaa-org/pyEDAA.Launcher?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/edaa-org/pyEDAA.Launcher

.. # Libraries - source rank
.. |SHIELD:svg:Launcher-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/pyEDAA.Launcher?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.Launcher/sourcerank
.. |SHIELD:png:Launcher-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/pyEDAA.Launcher?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.Launcher/sourcerank

.. # PyPI tag
.. |SHIELD:svg:Launcher-pypi-tag| image:: https://img.shields.io/pypi/v/pyEDAA.Launcher?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyEDAA.Launcher/
.. |SHIELD:png:Launcher-pypi-tag| image:: https://raster.shields.io/pypi/v/pyEDAA.Launcher?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyEDAA.Launcher/

.. # PyPI project status
.. |SHIELD:svg:Launcher-pypi-status| image:: https://img.shields.io/pypi/status/pyEDAA.Launcher?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:Launcher-pypi-status| image:: https://raster.shields.io/pypi/status/pyEDAA.Launcher?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22

.. # PyPI Python versions
.. |SHIELD:svg:Launcher-pypi-python| image:: https://img.shields.io/pypi/pyversions/pyEDAA.Launcher?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:Launcher-pypi-python| image:: https://raster.shields.io/pypi/pyversions/pyEDAA.Launcher?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22

.. # Libraries - status
.. |SHIELD:svg:Launcher-lib-status| image:: https://img.shields.io/librariesio/release/pypi/pyEDAA.Launcher?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.Launcher
.. |SHIELD:png:Launcher-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/pyEDAA.Launcher?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.Launcher

.. # Requires - status
.. |SHIELD:svg:Launcher-req-status| image:: https://img.shields.io/requires/github/edaa-org/pyEDAA.Launcher?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/edaa-org/pyEDAA.Launcher/requirements/?branch=main
.. |SHIELD:png:Launcher-req-status| image:: https://raster.shields.io/requires/github/edaa-org/pyEDAA.Launcher?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/edaa-org/pyEDAA.Launcher/requirements/?branch=main

.. # Documentation license
.. |SHIELD:svg:Launcher-doc-license| image:: https://img.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: Doc-License.html
.. |SHIELD:png:Launcher-doc-license| image:: https://raster.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Launcher/blob/main/doc/Doc-License.rst

.. # GHPages - read now
.. |SHIELD:svg:Launcher-ghp-doc| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=edaa-org.github.io%2FpyEDAA.Launcher&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fedaa-org.github.io%2FpyEDAA.Launcher%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://edaa-org.github.io/pyEDAA.Launcher/
.. |SHIELD:png:Launcher-ghp-doc| image:: https://raster.shields.io/website?longCache=true&style=flat-square&label=edaa-org.github.io%2FpyEDAA.Launcher&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fedaa-org.github.io%2FpyEDAA.Launcher%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://edaa-org.github.io/pyEDAA.Launcher/

.. # Gitter
.. |SHIELD:svg:Launcher-gitter| image:: https://img.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
.. |SHIELD:png:Launcher-gitter| image:: https://raster.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
